#!/usr/bin/python3

"""
This script uses epubZip function of OpenAccess_EPUB to zip an ePub directory
into a correctly packaged .epub file.
"""

from OpenAccess_EPUB.utils import epubZip
import sys
import os.path

usage = 'usage: epubzip ' + os.path.join('zip', 'this', 'dir')

def main():
    if len(sys.argv) > 2 or len(sys.argv) == 0:
        print(usage)
        sys.exit(1)
    else:
        epubZip(sys.argv[1])

if __name__ == '__main__':
    main()