#!/usr/bin/env python3

"""
This script uses epubZip function of OpenAccess_EPUB to zip an ePub directory
into a correctly packaged .epub file.
"""

from openaccess_epub.utils import epub_zip
import sys
import os

usage = 'usage: epubzip ' + os.path.join('zip', 'this', 'dir')

def main():
    if len(sys.argv) > 2 or len(sys.argv) == 0:
        print(usage)
        sys.exit(1)
    else:
        epub_zip(sys.argv[1])

if __name__ == '__main__':
    main()