#!/usr/bin/python

"""
This script uses epubZip function of OpenAccess_EPUB to zip an ePub directory
into a correctly packaged .epub file.
"""

from OpenAccess_EPUB.utils import epubZip
import sys

def main():
    epubZip(sys.argv[1])

if __name__ == '__main__':
    main()