#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
This script is used to configure or reconfigure the global settings for use by
OpenAccess_EPUB.
"""

import sys

if __name__ == '__main__':
    from openaccess_epub.quickstart import main
    sys.exit(main(sys.argv))
