#!/usr/bin/env python3

import openaccess_epub as oae
import openaccess_epub.utils as utils
from openaccess_epub.settings import *
import os.path
import logging
import shutil

#Import the global config file as a module
import imp
config_path = os.path.join(CACHE_LOCATION, 'config.py')
try:
    config = imp.load_source('config', config_path)
except IOError:
    print('Could not find {0}, please run oae-quickstart'.format(config_path))
    sys.exit()

def main():
    """The main method of the launch script"""
    args = oae.OAEParser()
    #Configure logging, 
    if args.input:
        logname = os.path.splitext(os.path.basename())[0] + '.log'
        logpath = os.path.join(args.output, logname)
    elif args.batch:
        logname = utils.getFileRoot(args.batch) + '.log'
        logpath = os.path.join(args.batch, logname)
    elif args.parallel_batch:
        logname = utils.getFileRoot(args.parallel_batch) + '.log'
        logpath = os.path.join(args.parallel_batch, logname)
    elif args.zip:
        logname = utils.getFileRoot(args.zip) + '.log'
        logpath = os.path.join(args.output, logname)
    logging.basicConfig(filename=logpath, level=logging.DEBUG)
    logging.info('openaccess_epub Log v.{0}'.format(oae.__version__))
    #Run the main script
    oae.main(args)


if __name__ == '__main__':
    main()
